=== legopitstop/Javascript/libs/Sprite/schema.json
{
    "$id": "https://cdn.jsdelivr.net/gh/legopitstop/Javascript/libs/Sprite/schema.json",
    "$schema": "http://json-schema.org/draft-07/schema",
    "description": "JSON schmea for textures.",
    "type": "object",
    "default": {},
    "required": [
        "textures",
        "file",
        "width",
        "height"
    ],
    "properties": {
        "file": {
            "description": "The sprite file that conatins all the items.",
            "type": "string"
        },
        "width": {
            "description": "The width of one item in the sprite",
            "type": "integer"
        },
        "height": {
            "description": "The height of one item in the sprite",
            "type": "integer"
        },
        "textures": {
            "description": "A list of textures that the sprite contains.",
            "type": "object",
            "additionalProperties": {
                "description": "The id of the texture.",
                "type": "array",
                "maxItems": 2,
                "minItems": 2,
                "items": {
                    "description": "The UV of the image. example: [1,1] will be the top left. [2,1] will be the next texture to the right.",
                    "type": "integer",
                    "default": 1,
                    "minimum": 1
                }
            }
        }
    }
}

=== legopitstop/Javascript/libs/Sprite/minecraft/sprite.json
{
    "$schema": "https://cdn.jsdelivr.net/gh/legopitstop/Javascript/libs/Sprite/schema.json",
    "file": "https://cdn.jsdelivr.net/gh/legopitstop/Javascript/libs/Sprite/minecraft/sprite.png",
    "width": 32,
    "height": 32,
    "textures": {
        "minecraft:end_stone_brick_wall": [24,1],
        "minecraft:prismarine_wall": [28,1],
        "minecraft:diamond_horse_armor": [29,1],
        "minecraft:red_nether_brick_wall": [30,1],
        "minecraft:golden_horse_armor": [2,2],
        "minecraft:iron_horse_armor": [7,2],
        "minecraft:jugnle_fence_gate": [23,2],
        "minecraft:honey_bottle": [29,2],
        "minecraft:honeycomb": [30,2],
        "minecraft:beehive": [31,2],
        "minecraft:beenest": [32,2],
        "minecraft:honey_block": [2,4],
        "minecraft:honeycomb_block": [3,4],
        "minecraft:trident.damaged": [4,4],
        "minecraft:brick_block": [14,4],
        "minecraft:netherite_block": [4,5],
        "minecraft:ancient_debris": [6,5],
        "minecraft:netherite_ingot": [7,5],
        "minecraft:netherite_scrap": [8,5],
        "minecraft:netherite_axe": [9,5],
        "minecraft:netherite_hoe": [10,5],
        "minecraft:netherite_pickaxe": [11,5],
        "minecraft:netherite_shovel": [12,5],
        "minecraft:netherite_sword": [13,5],
        "minecraft:netherite_boots": [14,5],
        "minecraft:netherite_chestplate": [15,5],
        "minecraft:netherite_helmet": [16,5],
        "minecraft:netherite_leggings": [17,5],
        "minecraft:crimson_planks": [18,5],
        "minecraft:warped_planks": [19,5],
        "minecraft:basalt": [20,5],
        "minecraft:crimson_nylium": [21,5],
        "minecraft:crimson_stem": [22,5],
        "minecraft:shroomlight": [23,5],
        "minecraft:soul_soil": [24,5],
        "minecraft:warped_nylium": [25,5],
        "minecraft:warped_stem": [26,5],
        "minecraft:warped_wart_block": [27,5],
        "minecraft:soul_torch": [28,5],
        "minecraft:soul_lantern": [29,5],
        "minecraft:crimson_fungus": [30,5],
        "minecraft:warped_fungus": [31,5],
        "minecraft:crimson_vines": [32,5],
        "minecraft:crimson_fence": [1,6],
        "minecraft:crimson_slab": [2,6],
        "minecraft:crimson_stairs": [3,6],
        "minecraft:warped_fence": [4,6],
        "minecraft:warped_slab": [5,6],
        "minecraft:warped_stairs": [6,6],
        "minecraft:crimson_button": [7,6],
        "minecraft:crimson_door": [8,6],
        "minecraft:crimson_pressure_plate": [9,6],
        "minecraft:crimson_trapdoor": [10,6],
        "minecraft:warped_button": [11,6],
        "minecraft:warped_door": [12,6],
        "minecraft:warped_pressure_plate": [13,6],
        "minecraft:warped_trapdoor": [14,6],
        "minecraft:stripped_crimson_stem": [15,6],
        "minecraft:stripped_warped_stem": [16,6],
        "minecraft:crimson_sign": [17,6],
        "minecraft:warped_sign": [18,6],
        "minecraft:crimson_fence_gate": [19,6],
        "minecraft:warped_fence_gate": [20,6],
        "minecraft:netherite_axe.damaged": [21,6],
        "minecraft:netherite_boots.damaged": [22,6],
        "minecraft:netherite_chestplate.damaged": [23,6],
        "minecraft:netherite_helmet.damaged": [24,6],
        "minecraft:netherite_hoe.damaged": [25,6],
        "minecraft:netherite_leggings.damaged": [26,6],
        "minecraft:netherite_pickaxe.damaged": [27,6],
        "minecraft:netherite_shovel.damaged": [28,6],
        "minecraft:netherite_sword.damaged": [29,6],
        "minecraft:crimson_roots": [30,6],
        "minecraft:?": [31,6],
        "minecraft:warped_roots": [32,6],
        "minecraft:target": [4,7],
        "minecraft:crying_obsidian": [5,7],
        "minecraft:crimson_hyphae": [6,7],
        "minecraft:warped_hyphae": [7,7],
        "minecraft:stripped_crimson_hyphae": [8,7],
        "minecraft:stripped_warped_hyphae": [9,7],
        "minecraft:nether_gold_ore": [10,7],
        "minecraft:twising_vines": [11,7],
        "minecraft:polished_basalt": [14,7],
        "minecraft:respawn_anchor": [15,7],
        "minecraft:sea_lantern": [17,7],
        "minecraft:encahntment_table": [22,7],
        "minecraft:creeper_head": [23,7],
        "minecraft:dragon_head": [24,7],
        "minecraft:stone": [27,8],
        "minecraft:stone_brick_slab": [5,30],
        "minecraft:player_head": [25,7],
        "minecraft:lodestone": [30,7],
        "minecraft:strider_spawn_egg": [31,7],
        "minecraft:warped_fungus_on_a_stick": [32,7],
        "minecraft:blackstone": [4,9],
        "minecraft:enchanted_golden_apple": [5,9],
        "minecraft:piglin_brute_spawn_egg": [6,9],
        "minecraft:chiseled_nether_bricks": [13,9],
        "minecraft:chiseled_blackstone_bricks": [14,9],
        "minecraft:cracked_nether_bricks": [15,9],
        "minecraft:cracked_blackstone_bricks": [16,9],
        "minecraft:gilded_blackstone": [17,9],
        "minecraft:polished_blackstone": [18,9],
        "minecraft:polished_blackstone_bricks": [19,9],
        "minecraft:blackstone_slab": [20,9],
        "minecraft:blackstone_stairs": [21,9],
        "minecraft:blackstone_wall": [22,9],
        "minecraft:polished_blackstone_brick_slab": [23,9],
        "minecraft:polished_blackstone_brick_stairs": [24,9],
        "minecraft:polished_blackstone_brick_wall": [25,9],
        "minecraft:polished_blackstone_slab": [26,9],
        "minecraft:polished_blackstone_stairs": [27,9],
        "minecraft:polished_blackstone_wall": [28,9],
        "minecraft:polished_blackstone_button": [29,9],
        "minecraft:polished_blackstone_pressure_plate": [30,9],
        "minecraft:soul_campfire": [31,9],
        "minecraft:quartz_bricks": [32,9],
        "minecraft:music_disc_pigstep": [1,10],
        "minecraft:chain": [2,10],
        "minecraft:potion": [22,10],
        "minecraft:lingering_potion": [10,11],
        "minecraft:splash_potion": [30,11],
        "minecraft:nether_star": [3,12],
        "minecraft:leather_horse_armor": [26,12],
        "minecraft:warped_fungus_on_a_stick.damaged": [30,12],
        "minecraft:knowledge_book": [1,13],
        "minecraft:goat_horn": [6,13],
        "minecraft:powder_snow": [7,13],
        "minecraft:goat_spawn_egg": [8,13],
        "minecraft:amethyst_cluster": [9,13],
        "minecraft:amethyst_shard": [10,13],
        "minecraft:black_candle": [11,13],
        "minecraft:amethyst_block": [12,13],
        "minecraft:blue_candle": [13,13],
        "minecraft:brown_candle": [14,13],
        "minecraft:budding_amethyst_block": [15,13],
        "minecraft:candle": [16,13],
        "minecraft:copper_block": [17,13],
        "minecraft:cut_copper": [18,13],
        "minecraft:cut_copper_slab": [19,13],
        "minecraft:cut_copper_stairs": [20,13],
        "minecraft:cyan_candle": [21,13],
        "minecraft:gray_candle": [22,13],
        "minecraft:green_candle": [23,13],
        "minecraft:large_amethyst_cluster": [24,13],
        "minecraft:light_blue_candle": [25,13],
        "minecraft:light_gray_candle": [26,13],
        "minecraft:exposed_copper": [27,13],
        "minecraft:exposed_cut_copper": [28,13],
        "minecraft:exposed_cut_copper_slab": [29,13],
        "minecraft:exposed_cut_copper_stairs": [30,13],
        "minecraft:lightning_rod": [31,13],
        "minecraft:lime_candle": [32,13],
        "minecraft:magenta_candle": [1,14],
        "minecraft:medium_amethyst_cluster": [2,14],
        "minecraft:orange_candle": [3,14],
        "minecraft:pink_candle": [4,14],
        "minecraft:purple_candle": [5,14],
        "minecraft:red_candle": [6,14],
        "minecraft:weathered_cut_copper_slab": [7,14],
        "minecraft:weathered_copper": [8,14],
        "minecraft:weathered_cut_copper": [9,14],
        "minecraft:weathered_cut_copper_stairs": [10,14],
        "minecraft:small_amethyst_cluster": [11,14],
        "minecraft:spyglass": [12,14],
        "minecraft:bundle.full": [13,14],
        "minecraft:bundle.half": [14,14],
        "minecraft:tinted_glass": [15,14],
        "minecraft:calcite": [16,14],
        "minecraft:tuff": [17,14],
        "minecraft:powder_snow_bucket": [18,14],
        "minecraft:dripstone_block": [19,14],
        "minecraft:pointed_dripstone": [20,14],
        "minecraft:white_candle": [21,14],
        "minecraft:yellow_candle": [22,14],
        "minecraft:skulk_sensor": [23,14],
        "minecraft:axolotl_spawn_egg": [24,14],
        "minecraft:oxidized_copper": [25,14],
        "minecraft:oxidized_cut_copper": [26,14],
        "minecraft:oxidized_cut_copper_slab": [27,14],
        "minecraft:oxidized_cut_copper_stairs": [28,14],
        "minecraft:axeolotl_bucket": [29,14],
        "minecraft:bundle": [30,14],
        "minecraft:copper_ore": [1,15],
        "minecraft:copper_ingot": [2,15],
        "minecraft:glow_item_frame": [6,15],
        "minecraft:glow_lichen": [7,15],
        "minecraft:glow_ink_sac": [8,15],
        "minecraft:glow_spawn_egg": [9,15],
        "minecraft:glowberries": [12,15],
        "minecraft:moss": [13,15],
        "minecraft:moss_carpet": [14,15],
        "minecraft:rooted_dirt": [15,15],
        "minecraft:azalea_bush": [16,15],
        "minecraft:azalea_leaves": [17,15],
        "minecraft:big_dripleaf": [18,15],
        "minecraft:flowering_azalea_bush": [19,15],
        "minecraft:flowering_azalea_leaves": [20,15],
        "minecraft:hanging_roots": [21,15],
        "minecraft:small_dripleaf": [22,15],
        "minecraft:spore_blossom": [23,15],
        "minecraft:chisled_deepslate_bricks": [9,16],
        "minecraft:deepslate_brick_slab": [10,16],
        "minecraft:deepslate_brick_stairs": [11,16],
        "minecraft:deepslate_brick_wall": [12,16],
        "minecraft:deepslate_bricks": [13,16],
        "minecraft:cobbled_deepslate_slab": [14,16],
        "minecraft:cobbled_deepslate_stairs": [15,16],
        "minecraft:deepslate_tile_slab": [16,16],
        "minecraft:deeplstae_tile_stairs": [17,16],
        "minecraft:deepslate_tile_wall": [18,16],
